.travis.yml

Why?
JRuby takes significantly longer to run the test suite; this ensures
that we use MRI instead of JRuby as the wrapper when running non-JRuby.

Update Travis build matrix to use CRuby on the appropriate Ruby versions

---

lib/factory_girl/decorator.rb
spec/acceptance/initialize_with_spec.rb

Why?
When the decorated @component is also a decorated object, and
FactoryGirl::Decorator#method_missing calls @component#send and a block
is present, the block needs to be sent appropriately.
Closes #816

Fix FactoryGirl::Decorator#send to pass blocks

---

README.md

FactoryGirl installation should occur through Bundler, so it can resolve
dependencies correctly.
When installing manually, include a caveat when installing on older
Rubies on how to handle breakages in the README.
Resolves #929, Resolves #928

Reprioritize how to install and add caveat for AS 5.0

---

lib/factory_girl/strategy_syntax_method_registrar.rb
spec/acceptance/create_list_spec.rb

Closes #889
`create_list` was failing abruptly if the second argument was not count. Give a descriptive error message for this case.

Add error message when count is missing for create_list

---

GETTING_STARTED.md

Aside from being unclear, this also seemed to be effecting the code block parsing for the remainder of the file (see screenshots below)
--------------
**The hosted version:**
**My version previewed in** `YARD`:

Remove 'RSpec' heading from code block

---

GETTING_STARTED.md

I was reading through the Getting Started guide and noticed that Inheritance is introduced in the Associations section which precedes the Inheritance section. Since the Inheritance section is small I think it flows better to introduce it first, then it makes more sense when you encounter it in the Associations section.

Moved inheritance above associations in the Getting Started guide

---

lib/factory_girl.rb
lib/factory_girl/configuration.rb
lib/factory_girl/evaluator.rb
spec/acceptance/build_spec.rb
spec/acceptance/build_stubbed_spec.rb
spec/acceptance/register_strategies_spec.rb

Picking up where https://github.com/thoughtbot/factory_girl/pull/749 left off.
This PR adds a `FactoryGirl.use_parent_strategy` configuration option, allowing factory associations to follow the parent's build strategy.  Previously, all factory associations were
created, regardless of whether the parent was persisted to the database.
The configuration option is off by default, so there is no change to the current behavior.

Add use_parent_strategy option for building associations

---

GETTING_STARTED.md

Everywhere else the gem is referred to as "factory_girl" instead of "FactoryGirl".

refer to gem itself consistently

---

.travis.yml
spec/spec_helper.rb

I noticed a couple of tests fail intermittently whilst setting up the project to contribute. 
Using `rspec --bisect` to hunt down the minimal reproductions:
```
bundle exec rspec './spec/acceptance/define_child_before_parent_spec.rb[1:1]' './spec/factory_girl/definition_spec.rb[3:1]' --seed 50350
``` 
```
Run options: include {:ids=>{"./spec/acceptance/define_child_before_parent_spec.rb"=>["1:1"], "./spec/factory_girl/definition_spec.rb"=>["3:1"]}}
Randomized with seed 50350
.F
Failures:
1) defining a child factory before a parent creates admin factories correctly
Failure/Error: declarations.attributes
Mocha::ExpectationError:
unexpected invocation: #<Mock:declaration list>.attributes()
Finished in 0.19463 seconds (files took 0.40745 seconds to load)
2 examples, 1 failure
```
```
bundle …
```

Fix test order dependent failures with seeds 50350 + 48550

---

GETTING_STARTED.md
lib/factory_girl.rb
lib/factory_girl/linter.rb
spec/acceptance/lint_spec.rb

When using FactoryGirl with non-ActiveRecord objects it would be useful to allow the strategy used for linting to be specified:
```ruby
FactoryGirl.lint strategy: :build
```
---
~~Based on #1018 to get a green build. Will point base branch to `master` if the other PR is resolved.~~

Linting factory strategy

---

GETTING_STARTED.md

This will make sure to return whatever the system call returned and it's useful to chain shell calls, etc.

Improve lint rake task example to return proper exit code

---

GETTING_STARTED.md

The `cleaning` method already ensures cleaning and provides for a way to write better looking code.
This should be 100% equivalent to previous example.

Simplify DatabaseCleaner code example for linter

---

spec/factory_girl/find_definitions_spec.rb

What?
=====
This updates the test asserting alphabetical load order by using the
correct RSpec syntax.

Update ordered assertion test

---

features/support/factories.rb

What?
=====
Rails' migrations now support versioning; this updates the superclass to
conditionally swap based on versions of Rails to remove a deprecation
warning.

Update migration base class to work with new versions of Rails

---

Gemfile.lock

There's a known vulnerability in 0.9.9.
https://nvd.nist.gov/vuln/detail/CVE-2017-17042

Update locked yard to 0.9.12.

---

GETTING_STARTED.md

Hello!
The current GETTING_STARTED file has a somewhat confusing table of contents, with the specific names of each test framework as big top-level content, and then the main content (like "Defining factories") as small bullets nested below "minitest-rails":
This PR makes the test suite names sub-headers of "configure your test suite" and makes what I think is the main content top-level headers:
I think this just brings the file more in line with the intent, but happy to discuss if I'm wrong about that!
(Also note, this will have to land on Rubygems to be live on the documentation site, since the link to GETTING_STARTED in the README is hard-coded.)

Improve GETTING_STARTED table of content hierarchy

---

GETTING_STARTED.md

The suggested [Rake task for linting factories](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#linting-factories) doesn't currently support chaining Rake tasks.
For example, if one's `Rakefile` contains:
```ruby
task default: ["factory_bot:lint", :spec]
```
Regardless of whether the linting passes or fails, the second task will never be executed because the linting task `exit`s:
```ruby
exit $?.exitstatus
```
To allow Rake task chaining it'd be preferable to:
```ruby
fail if $?.exitstatus.nonzero?
```
Rake will not-attempt any following tasks & exit with a non-zero exit status if the linting failed. If the linting passes then following tasks will be run.
If the linting Rake task is run alone then it'll exit with status `0` when linting passes, and status `1` when …

Fix linting Rake task to allow task chaining

---

GETTING_STARTED.md

As noted in the original PR #1105, separating the Rails and non-Rails
configurations makes it easier to copy and paste.
We are also removing the bit about requiring `support/factory_bot`. I
think think it is outside the scope of this documentation to suggest
splitting of RSpec configuration into multiple files. We don't specify
file names for the other test configurations. Also, this line has
led to more confusion than it is probably worth, and has come up
in several PRs: #987, #1025, #1081, #1085, and #1091.
Co-authored-by: Jarvis Johnson <jarviscjohnson@gmail.com>
Co-authored-by: Daniel Colson <danieljamescolson@gmail.com>

Simplify RSpec configuration instructions

---

README.md

Same as https://github.com/thoughtbot/factory_bot_rails/pull/279, but for `factory_bot` instead of `factory_bot_rails`.
[![Gem Version](https://badge.fury.io/rb/factory_bot.svg)](http://badge.fury.io/rb/factory_bot) [![SemVer](https://api.dependabot.com/badges/compatibility_score?dependency-name=factory_bot&package-manager=bundler&version-scheme=semver)](https://dependabot.com/compatibility-score.html?dependency-name=factory_bot&package-manager=bundler&version-scheme=semver)
Also cleans up the link style to match `factory_bot_rails`.

Add version and semver stability badges to README

---

lib/factory_bot/definition_proxy.rb
spec/acceptance/static_attribute_deprecation_spec.rb

On `stderr` a message will be displayed like:
```
DEPRECATION WARNING: Static attributes will be removed in FactoryBot 5.0. Please use dynamic attributes instead. Static attribute=:rockstar value=true (called from block (5 levels) in <top (required)> at /Users/oli/workspace/factory_bot/spec/acceptance/transient_attributes_spec.rb:11)
```
The caller / callsite in the message is set to where the attribute is declared. 
For further background on the motivation behind this change, see this commit: https://github.com/thoughtbot/factory_bot/commit/eaf2b403f35b2b7c9a014675d15d8b2646bd0601

Print warning about static attribute deprecation

---

lib/factory_bot/definition_proxy.rb

Fixes #1160
https://github.com/rubocop-hq/rubocop-rspec/pull/666 was merged. I
would like to wait until the next version of rubocop-rspec is
released, then release factory_bot 4.11 with this deprecation.

Include rubocop-rspec autocorrect in deprecation

---

factory_bot.gemspec

With `git ls-files` we were still including unneeded dotfiles and
appraisal files. This switches to a whitelist of files included in the
gem, rather than a blacklist. I also tried to make RuboCop happy while I
was in here.

Don't include extra files in the gem

---

lib/factory_bot/configuration.rb
lib/factory_bot/definition.rb
lib/factory_bot/definition_proxy.rb
spec/acceptance/sequence_resetting_spec.rb
spec/factory_bot/definition_proxy_spec.rb
spec/factory_bot/definition_spec.rb

This was originally opened as #1078, but this addresses the review
comments on that PR.
By registering the inline sequences, we allow them to get rewound with
`FactoryBot.rewind_sequences`. We register them with
`__#{factory_name}_#{sequence_name}__` to avoid conflicting with any
reasonably named global sequences, and to hint that we should not be
generating values from these sequences directly.
Co-authored-by: Damian Le Nouaille <dam@dln.name>
Co-authored-by: Damian Galarza <galarza.d@gmail.com>

Register inline sequence to allow for rewinding

---

Gemfile.lock
spec/acceptance/sequence_resetting_spec.rb

Defining User classes in these tests was causing warnings about redefining
constants elsewhere in the suite.

Avoid defining classes without test helpers

---

GETTING_STARTED.md

Fix #1165 
This list does not include private methods and the methods in the ``UNPROXIED_METHODS`` constant. Should we include these as well? It does include delegates and attr_reader.

Add list of reserved word to getting started guide

---

lib/factory_bot.rb
lib/factory_bot/configuration.rb
lib/factory_bot/definition_proxy.rb
spec/acceptance/transient_attributes_spec.rb

Since we have started work on factory_bot 5, we no longer need to keep
these deprecated methods around.

Remove deprecated methods

---

lib/factory_bot/strategy/stub.rb

factory_bot 5 only supports Rails 4.2 and higher,
and #clear_changes_information has been around since then
(https://github.com/rails/rails/commit/66d0a0153578ce760d822580c5b8c0b726042ac2).
Fixes #941, since we will are no longer managing any instance variables.

Remove backport for ActiveModel:Dirty

---

lib/factory_bot/definition_proxy.rb
spec/factory_bot/definition_proxy_spec.rb

Inside `super` Ruby calls `inspect`, but since we have undefined
`inspect` on the definition proxy we end up declaring an implicit
`inspect` attribute. We do the same thing with `methods` and
`singleton_methods`, and then `inspect` again. By the time we finally
see the NoMethodError, we see it on a
`FactoryBot::Declaration::Implicit` instead of the definition proxy.
By raising the NoMethodError manually we avoid this nonsense and have
the added benefit of showing the name of the factory where the missing
method came from.

Manually raise NoMethodError in definition proxy

---

lib/factory_bot/attribute.rb
lib/factory_bot/errors.rb
spec/factory_bot/attribute_spec.rb
spec/factory_bot/definition_proxy_spec.rb

This warning made sense when we had static attributes, since
somebody might try to write something like:
```rb
factory :composer do
self.name = "Daniel"
end
```
That would create a static declaration when the factory was defined,
then raise the error about avoiding writers when the factory was run.
Now this code will raise a NoMethodError right away when the factory is
being defined.

Remove warning about setter methods

---

.rubocop.yml
lib/factory_bot/aliases.rb
lib/factory_bot/strategy_syntax_method_registrar.rb
spec/acceptance/initialize_with_spec.rb

Continue addressing #1202 
Addresses all the 'Performance' cops. These were all straightforward to fix.
I originally fixed the `Performance/RegexpMatch` offense by using the suggested fix (`Regexp#match?`), but it turns out that the CI uses Ruby 2.3, which doesn't have that method. I fixed this by setting the `TargetRubyVersion` in `.rubocop.yml` to 2.3. The other way to do this is by adding a `.ruby-version` file to the project, then Rubocop will just use what version is specified there.
I looked into fixing the `Naming/MemoizedInstanceVariableName` cop as well in this PR, but it doesn't really fit into what Rubocop wants. The only thing I could think of would be to add a `rubocop:disable` comment, but I'm not sure if that's what the maintainers want.

[Rubocop] Performance Cop Offenses

---

.rubocop.yml
spec/support/macros/define_constant.rb

RuboCop didn't seem to like having memoization in the
`default_constants` method that didn't match the method name. This
satisfies RuboCop, and saves us an array allocation or two when we run
specs that don't use any of these helpers.

Use dedicated methods for memoized values

---

.rubocop.yml
lib/factory_bot/declaration_list.rb
lib/factory_bot/evaluator.rb
lib/factory_bot/null_object.rb
lib/factory_bot/syntax/default.rb
spec/acceptance/activesupport_instrumentation_spec.rb
spec/acceptance/build_list_spec.rb
spec/acceptance/callbacks_spec.rb
spec/acceptance/create_list_spec.rb
spec/acceptance/sequence_context_spec.rb
spec/factory_bot/evaluator_class_definer_spec.rb
spec/factory_bot/factory_spec.rb
spec/support/macros/define_constant.rb

Continue addressing #1202
Addresses all of the 'Lint' cops. For most of these fixes, I just used the suggested Rubocop fix, but on some others I took them one step further. For example, using `#each` instead of `#each_with_index` when the index wasn't used.
This is my first time contributing, so let me know if I missed any steps.

[Rubocop] Lint Cop Offenses

---

.rubocop.yml
Rakefile
factory_bot.gemspec
features/support/factories.rb
lib/factory_bot/aliases.rb
lib/factory_bot/attribute_assigner.rb
lib/factory_bot/configuration.rb
lib/factory_bot/declaration_list.rb
lib/factory_bot/definition_proxy.rb
lib/factory_bot/factory.rb
lib/factory_bot/factory_runner.rb
lib/factory_bot/linter.rb
lib/factory_bot/strategy/null.rb
lib/factory_bot/strategy/stub.rb
spec/acceptance/attribute_existing_on_object_spec.rb
spec/acceptance/build_stubbed_spec.rb
spec/acceptance/create_spec.rb
spec/acceptance/nested_attributes_spec.rb
spec/acceptance/overrides_spec.rb
spec/acceptance/transient_attributes_spec.rb
spec/factory_bot/definition_proxy_spec.rb
spec/factory_bot/evaluator_class_definer_spec.rb
spec/support/macros/define_constant.rb
spec/support/matchers/declaration.rb
spec/support/shared_examples/strategy.rb

Continue addressing #1202 
Addresses most of the 'Style' cops. I opted to skip a couple cops, because I don't have enough knowledge about them to know how to correctly fix them. The first is the `Style/MethodMissing` cop. I saw [this thread](https://github.com/rubocop-hq/rubocop/issues/3760) and thought that that same issue may apply. If anyone has a suggestion on what route to go on this, I can make the change if requested.
The other is the `Style/StringLiterals` cop. There is a big split on strings that use single and double quotes, so I'm not sure if we want to settle on one and use it. If someone tells me the preference, I can easily fix this as well.
I also had to omit fixing the `Style/RedundantBegin` cop because after making the change, Hound complained about invalid syntax. I'm …

[Rubocop] Style Cop Offenses

---

.rubocop.yml
lib/factory_bot/linter.rb
spec/acceptance/lint_spec.rb

I removed the exclusionary line from the rubocop file, and then ran `rubocop -a`.
On visually inspecting the resulting output, I manually adjusted the offenses in `lint_spec` as the autocorrect did some weird things with it.
I also took a look at the `Layout/SpaceInsideHashLiteralBraces` TODO, and couldn't find the offense. Was it possibly fixed in a different PR? Can we remove that line from the rubocop file list?

Rubocop: Fix Layout/IndentHeredoc issues

---

lib/factory_bot/attribute_assigner.rb
lib/factory_bot/decorator/attribute_hash.rb
spec/acceptance/initialize_with_spec.rb
spec/factory_bot/decorator/attribute_hash_spec.rb

Fixes #1155
Defining an attribute called 'attributes', then referring to that
attribute in `initialize_with` was causing `AttributeHash#attributes`
to call itself recursively.

Avoid recursive call to AttributeHash#attributes

---

lib/factory_bot/strategy/stub.rb
spec/acceptance/build_stubbed_spec.rb

Closes  #1058
Before this change the build_stubbed strategy would override `#created_at` and `#updated_at`. The new methods store the times in `@created_at` and `@updated_at` instance variables, rather than in `@attributes`. This could cause unexpected behavior when using `#created_at=` or #updated_at=`. As an example, this would fail:
```rb
post = build_stubbed(:post)
timestamp = 1.month.ago
post.created_at = timestamp
expect(post.created_at).to eq(timestamp)
```
Instead of overriding these methods, we can have build_stubbed set the values using `#created_at=` and `#updated_at=`. We need to do this after calling `clear_changes_information` or else we end up with an incorrect timezone.

Allow timestamp assignment in stubbed models

---

lib/factory_bot/declaration/association.rb
lib/factory_bot/declaration/dynamic.rb
lib/factory_bot/declaration/implicit.rb
spec/acceptance/associations_spec.rb
spec/factory_bot/declaration/association_spec.rb
spec/factory_bot/declaration/dynamic_spec.rb
spec/factory_bot/declaration/implicit_spec.rb

Closes #970
In this code we are passing an implicit declaration `user`, rather than
the symbol `:user`:
```rb
factory :post do
author factory: user
end
```
This will raise a confusing error:
`undefined method 'name' for :post:Symbol`.
This is coming from the implicit declaration `#==` method,
which ends up getting called [here](https://github.com/thoughtbot/factory_bot/blob/7925c47653b4e3c06661ffefac192efcf0c48144/lib/factory_bot/attribute_list.rb#L56).
This `#==` method wasn't ever designed to compare against
objects of different classes. I added some tests for all the declaration
classes to handle being compared against other kinds of objects.
Now we will get a more meaningful error `Trait not registered: user`
Co-authored-by: Dusan Orlovic <duleorlovic@gmail.com>

Raise more meaningful error for unregistered trait

---

lib/factory_bot/strategy/stub.rb
spec/acceptance/build_stubbed_spec.rb

To get timestamps for build_stubbed objects to behave the same as timestamps for real, persisted objects
e7f66fb2 fixed one problem and introduced a new one. Setting timestamps
after clearing changes information doesn't work, since using the
created_at and updated_at setters will change the object again. I added
some additional specs for this case (our only spec related to clearing
changes used an object without timestamps).
For the timezone problem, I did a little digging and realized the
casting behavior was actually correct. The reason it was behaving in a
different way than I was expecting is because we had
`time_zone_aware_attributes` set to false, whereas the AR railtie
[sets it to true](https://github.com/rails/rails/blob/54652d886ad1c9ffca36c6f2baadcdd6135ef4dd/activerecord/lib/act …

Set timestamps before clearing changes

---

GETTING_STARTED.md

Add documentation to the associations section to mention the `use_parent_strategy` configuration, and demonstrate it.

Document use_parent_strategy configuration

---

lib/factory_bot.rb
lib/factory_bot/linter.rb

This refactoring work should make adding the verbose linting option
(started in PR #1233) fairly simple.
I moved the linting option defaults into keyword argument defaults for
Linter#initialize. With keyword arguments we will now get an error if we
pass an option the Linter doesn't understand (we were doing exactly this
in one of our tests before 6e511597). Adding the verbose option will
involve adding one more keyword argument.

Refactor Linter to simplify adding verbose option

---

GETTING_STARTED.md
lib/factory_bot.rb
lib/factory_bot/linter.rb
spec/acceptance/lint_spec.rb

This has come up a few times, and I can see why it might be helpful to
have access to full backtraces when debugging a factory error uncovered
by `FactoryBot.lint`. But since most of the time I don't want the extra
noise from the backtrace, I added this as a verbose option.
The default message is still:
```
The following factories are invalid:
* user - undefined method `save!' for #<User:0x00007ff0cbc89100>
* admin - undefined method `save!' for #<User:0x00007ff0cbc73e40>
```
And with the verbose option (usually with more lines of backtrace):
```
The following factories are invalid:
* user - undefined method `save!' for #<User:0x00007ff0cbc89100>
/Users/.../factory_bot/lib/factory_bot/evaluation.rb:18:in `create'
/Users/.../factory_bot/lib/factory_bot/strategy/create.rb:12:in `block in …
```

Add option for verbose linting

---

lib/factory_bot.rb
lib/factory_bot/configuration.rb
spec/acceptance/build_spec.rb
spec/acceptance/register_strategies_spec.rb
spec/acceptance/reload_spec.rb
spec/spec_helper.rb

Before this PR, `use_parent_strategy` was set on the configuration
instance. Since `FactoryBot.reload` wipes out the configuration, it also
ends up resetting `use_parent_strategy` back to `nil`.
This can cause problems when using factory_bot_rails with Spring, since
factory_bot_rails calls `FactoryBot.reload` each time Spring forks. If
`use_parent_strategy` is set in a file that Spring preloads, like in an
initializer, then the value will get wiped out.
With this PR, we set `use_parent_strategy` directly on FactoryBot,
rather than on the configuration instance, and so reloading no longer
has any effect.
Related to #1236 and #1240

Do not reset use_parent_strategy on reload

---

Gemfile
Gemfile.lock
factory_bot.gemspec
gemfiles/4.2.gemfile
gemfiles/4.2.gemfile.lock
gemfiles/5.0.gemfile
gemfiles/5.0.gemfile.lock
gemfiles/5.1.gemfile
gemfiles/5.1.gemfile.lock
gemfiles/5.2.gemfile
gemfiles/5.2.gemfile.lock

I consolidated all the development dependencies in the gemspec,
then ran `bundle update` and `appraisal install`.
I also got rid of unnecessary version constraints (I would rather just
the latest versions of things in development, and we can always add
constraints later if necessary), and removed the jruby-specific gems
since we aren't testing on jruby anymore.

Update development dependencies

---

lib/factory_bot.rb

I removed allow_class_lookup entirely in 2e0b476 when removing the
deprecated ability to lookup factories by class. But the upgrade to
fb 5 will be a bit more smooth if we deprecate the method first.

Deprecate allow_class_lookup

---

lib/factory_bot.rb
spec/factory_bot_spec.rb
spec/spec_helper.rb

Followup to https://github.com/thoughtbot/factory_bot/commit/d0208eda9c65cbc476a02d2f7503234195610005.
The `default:` option of `mattr_accessor` wasn't added until Rails 5.2, which means it has no effect on older versions and the default value of `FactoryBot.use_parent_strategy` in 5.0.0.rc1 is nil on those versions.

Set use_parent_strategy default to true explicitly

---

lib/factory_bot/syntax/methods.rb

> FactoryBot::Syntax::Methods was missing some documentation on the null
strategy and the *_pair methods. This adds in the documentation and
corresponding method directives.
>
> Further, add the missing &block parameter to the existing *_list directives.
This pull request improves the documentation available, so that users don't need to look through the source code to find out that there are `null` and `*_pair` methods available.
My personal interest in this is because RubyMine is able to use YARD documentation to help provide suggestions in auto completion, resolve methods, and to provide method documentation. Adding these missing directives will help improve the user experience.

Add documentation and YARD method directives

---

GETTING_STARTED.md

":true" was the symbol, so fix it.

Fix typo in GETTING_STARTED

---

lib/factory_bot.rb
lib/factory_bot/internal.rb
lib/factory_bot/reload.rb
lib/factory_bot/syntax/default.rb

The `FactoryBot` module has a mixture of methods that are meant for
public use, and methods that are meant only for internal use.
The methods meant for internal use are cluttering the
documentation, and may be confusing to people using the library.
This PR was prompted by [#1258]. Rather than introduce yet another
public method on `FactoryBot` meant only for internal use,
we can introduce a `FactoryBot::Internal` module,
and avoid generating documentation for the internal module.
The `FactoryBot::Internal.register_inline_sequence` method in [#1258]
will need access to the configuration instance, so this PR moves that
into `FactoryBot::Internal`. Eventually I plan to deprecate
`FactoryBot.configuration` and `FactoryBot.reset_configuration`, and to
move more of the `FactoryBot` methods into …

Introduce FactoryBot::Internal module

---

lib/factory_bot.rb
lib/factory_bot/configuration.rb
lib/factory_bot/definition_proxy.rb
lib/factory_bot/internal.rb
spec/acceptance/sequence_resetting_spec.rb
spec/factory_bot/definition_proxy_spec.rb

Fixes #1257
When sequence rewinding was first introduced in #1043 it only applied to
globally defined sequences. To get rewinding to work for inline
sequences as well we registered them "privately" in the global registry
in #1164. Unfortunately in #1164 we did not take inline sequences inside
traits into consideration. Since trait names are not unique, it is
possibly to get a `FactoryBot::DuplicateDefinitionError` when defining
two sequences that have the same name in two traits that have the same
name.
This PR abandons the idea of "privately" registering inline sequences,
and instead keeps a separate list of all the inline sequences just for
the purpose of rewinding them.
~~The downside here is that we are adding another public method to
FactoryBot. But I think it is similar enough to …

Allow inline sequences in traits to have same name

---

RELEASING.md

There is a thoughtbot resource that lays out info for announcing releases that we want to mention. 
Co-authored-by: Todd Morningstar <todd@thoughtbot.com>

Point to handbook section on gem release

---

lib/factory_bot/definition.rb
lib/factory_bot/factory_runner.rb
lib/factory_bot/trait.rb
spec/acceptance/traits_spec.rb
spec/support/matchers/trait.rb

Fixes [#1259]
Fixes [#1267]
In [#1156] we added support for looking up local traits with either a
symbol or string. This matches the lookup for factories and for global
traits.
We were calling `to_sym` on the trait arguments passed in when
building an object, assuming that those arguments would always respond
to `to_sym`. This leads to a confusing error message when passing an
object that doesn't respond to that method.
This PR replaces the confusing "NoMethodError: undefined method `to_sym`
for ..." with a more helpful "KeyError: Trait not registered: ...". It
ensures that all trait resolution is done using strings instead of
symbols, all objects should have a `to_s` method.
Co-authored-by: Sean Doyle <sean.p.doyle24@gmail.com>
[#1259]: …

Improve error message for resolving invalid traits

---

GETTING_STARTED.md

We have explicit association written as `association :author, factory: :user` everywhere 
except for polymorphic `association(:commentable, factory: :video)`
This PR aims to keep it consistent

Code style consistency for Polymorphic association

---

lib/factory_bot/evaluator.rb

In https://github.com/thoughtbot/factory_bot/pull/799, this call to `undef_method` was introduced to suppress the warning printed by Ruby when a method is redefined.
That warning is only printed when the method is already defined on the class in question; it isn't printed when the method was inherited from an ancestor, since overriding methods by shadowing them is a feature.
However, `method_defined?` returns true for inherited methods, which means we're sometimes undefining methods that wouldn't cause a warning.
If a factory defines an attribute named `object_id` (admittedly not a great idea), we will undefine the `object_id` method inherited from the `Object` class, and the following warning will be printed:
factory_bot/evaluator.rb:70: warning: undefining `object_id' may cause serious …

Only undefine methods that were previously defined

---

GETTING_STARTED.md

For new users who may trip over setup
I (was moving too fast and) put this in spec_helper and got an error. I ended up on [stackoverflow](https://stackoverflow.com/questions/48091582/ruby-gem-uninitialized-constant-factorybot) to fix the problem. Suggesting this line to help future users.

Add setup comment

---

README.md

Stackoverflow redirect to the new tag name: "factory-girl" gets redirected to "factory-bot"
No needs to mention the old tag name. The existing tag is line 58 (4 lines above).

Update README.md: remove StackOverflow old tag mention

---

GETTING_STARTED.md

Recent versions of rails allows to rely less on DatabaseCleaner, which is a good thing.
This updated way of  linting factory is inspired by this blog post 
https://www.nicholasjacques.io/blog/using-factorygirl-and-transactional-testing/

Don't rely on DatabaseCleaner for the rake task

---

lib/factory_bot/declaration/association.rb
spec/acceptance/associations_spec.rb

Closes https://github.com/thoughtbot/factory_bot/issues/1227
In this code we are passing an implicit declaration `user`, rather than
the symbol `:user`:
```rb
factory :post do
author factory: user
end
```
In https://github.com/thoughtbot/factory_bot/issues/1227 we improved the
error message from:
```rb
undefined method 'name' for :post:Symbol
```
to:
```rb
Trait not registered: user
```
But this still doesn't make it totally obvious what the error was.
Why are we trying to register a user trait?
With this PR we update the error message to:
```rb
Association 'author' received an invalid factory argument.
Did you mean? 'factory: :user'
```

Offer advice for association typo

---

lib/factory_bot/definition_proxy.rb
spec/factory_bot/definition_proxy_spec.rb

Some people upgrade straight from factory_bot < 4.11 to factory_bot >=
5.0 and miss the deprecation cycle for static attributes. I have gotten
some feedback that the NoMethodError is confusing. Since we know that in
most cases people are seeing the NoMethodError when trying to define
static attributes, we offer them a "Did you mean?"-style suggestion for
how they might update to dynamic attributes.
I removed the extra test for setter methods. It was a remnant of
something I had removed in #1200. I see no reason to have special
treatment for setters at this point.
Closes https://github.com/thoughtbot/factory_bot/issues/1272

Improve error for static attribute attempts

---

lib/factory_bot.rb
lib/factory_bot/definition.rb
lib/factory_bot/internal.rb
lib/factory_bot/syntax/default.rb
spec/factory_bot/internal_spec.rb
spec/factory_bot_spec.rb
spec/support/macros/deprecation.rb

Why:
These are essentially internal methods that should not be publicly
available from the base namespace.
One thing worth noticing is that the use of these methods internally was
almost exclusively in the `syntax/default` except for one use on the
`factory_bot/definition`.
Also, the deprecation silencing module was referring to the singleton
an instance of the ```ActiveRecord:: Deprecation``` class and not to the new
deprecation instance that was being used in the ```FactoryBot``` module.
This PR:
- Moves the `trait_by_name` and `register_trait` into the
`FactoryBot::Internal` module
- Deprecates uses of `trait_by_name`, `register_trait` and `traits` from
the `FactoryBot` module.
- Rename DEPRECATOR => Deprecation
This is one of the steps towards fixing [this
issue](#1281)

Move and deprecate trait methods from FactoryBot

---

lib/factory_bot.rb
lib/factory_bot/declaration/implicit.rb
lib/factory_bot/internal.rb
lib/factory_bot/syntax/default.rb
lib/factory_bot/syntax/methods.rb
spec/factory_bot/attribute/dynamic_spec.rb
spec/factory_bot/attribute/sequence_spec.rb
spec/factory_bot/declaration/implicit_spec.rb
spec/factory_bot/internal_spec.rb
spec/factory_bot_spec.rb

Why:
Another run of internal methods that should not be publicly
available from the base namespace.
This time the sequence involving methods were moved. It's worth noticing
that the ```Internal``` class is getting crowded. Maybe we can start
name-spacing the internal groups into modules under
```internal/sequence.rb``` ```internal/trait.rb``` and so on. Thoughts?
This PR:
- Moves the ```register_sequence```, ```sequence_by_name```,
```sequences``` and ```rewind_sequences``` to the
```FactoryBot::Internal``` module.
- Deprecates uses of ```register_sequence```, ```sequence_by_name```,
```sequences``` and ```rewind_sequences``` from the ```FactoryBot``` module.
This is one of the steps towards fixing [this issue](https://github.com/thoughtbot/factory_bot/pull/1285#1281)

Deprecate and move to Internal sequence methods

---

Gemfile.lock

Why:
A security vulnerability has been identified with the 0.9.19 version of
the yard gem. More details
[here](https://github.com/lsegal/yard/security/advisories/GHSA-xfhh-rx56-rxcr)
This PR:
Updates the yard gem version.

Update yard from 0.9.19 to 0.9.20

---

lib/factory_bot/strategy/stub.rb
spec/acceptance/stub_spec.rb
spec/support/macros/define_constant.rb

Fixes #1305
Before Rails 6 when the build_stubbed strategy assigned an id on a
record without a primary key column, the `id=` method would no-op, and
the record would end up looking like a new_record (i.e. `new_record?`
would return true because the id was nil).
This problem surfaced because of a [change in Rails 6][rails], which
caused `id=` to raise a potentially confusing
`ActiveModel::MissingAttributeError: can't write unknown attribute ''`
for records without a primary key column.
Since build_stubbed stubbed was calling `id=` for all instances,
regardless of whether they had primary keys, it was raising the above
error.
To avoid this error, we check whether the instance has a primary_key
defined before setting the id.
We also changed `persisted?` and `new_record?` to be less …

Avoid stubbing id for records without primary key

---

features/support/factories.rb
spec/support/macros/define_constant.rb

This PR is partly out of curiousity 📚  (I've always read about this mode but not used it), but it also makes specs faster (on my machine at least).
| Iteration | Before | After    |
|-----------|--------|----------|
| 1         | 7.974  | 6.294    |
| 2         | 7.727  | 6.292    |
| 3         | 7.684  | 6.320    |
| 4         | 7.813  | 6.345    |
| 5         | 8.207  | 6.278    |
| 6         | 7.918  | 6.229    |
| 7         | 7.785  | 6.249    |
| 8         | 7.856  | 6.281    |
| 9         | 7.894  | 6.273    |
| 10        | 7.767  | 6.287    |
| Avg       | 7.863  | 6.285    |
| Diff      |        | -20.066% |
Test command:
```
repeat 10 { time bundle exec rake 2>/dev/null } | grep total
```
https://www.sqlite.org/inmemorydb.html

Use sqlite in-memory DB in specs

---

Gemfile.lock
factory_bot.gemspec
gemfiles/4.2.gemfile.lock
gemfiles/5.0.gemfile.lock
gemfiles/5.1.gemfile.lock
gemfiles/5.2.gemfile.lock
gemfiles/6.0.gemfile.lock
spec/acceptance/build_stubbed_spec.rb
spec/factory_bot/strategy/stub_spec.rb
spec/spec_helper.rb
spec/support/matchers/be_about_now.rb

This PR is made up of two commits, which may make more sense reviewed invidiually:
1. Removes `TimeCop` in favour of `ActiveSupport::Testing::TimeHelpers` (removes a dev dependency from the project)
2. (Optional) Avoids freezing / travelling through time altogether
Happy to remove the second change from the PR if it's a step too far.

Remove Timecop / time travel

---

Appraisals
gemfiles/6.0.gemfile
gemfiles/6.0.gemfile.lock

https://weblog.rubyonrails.org/2019/7/30/Rails-6-0-rc2-released/

Appraise ActiveRecord 6.0.0.rc2

---

spec/acceptance/build_spec.rb
spec/acceptance/register_strategies_spec.rb
spec/acceptance/reload_spec.rb
spec/spec_helper.rb
spec/support/macros/deprecation.rb
spec/support/macros/temporary_assignment.rb

I noticed in `spec_helper.rb` there's a global `around` to reset some state:
https://github.com/thoughtbot/factory_bot/blob/eb6bccb3e3cdeef6948cfb7b187e084982318075/spec/spec_helper.rb#L24-L31
This PR proposes switching to a block-based helper to safely adjust global state in the specs which need to do so. When the block is completed, the value is reset.

[Tests] Adjust global state in blocks

---

lib/factory_bot/declaration/implicit.rb
lib/factory_bot/errors.rb
lib/factory_bot/trait.rb
spec/acceptance/traits_spec.rb

We want to check if any attributes of a new trait definition matches the name of
the trait. Raise an error if so, to avoid a recursive call to the trait. A fix to:
https://github.com/thoughtbot/factory_bot/issues/1238

Raise error when a trait is self-referencing

---

spec/factory_bot/aliases_spec.rb

For reference:
TL;DR- there is consensus within thoughtbot that RSpec's `subject`, `before`, and `let` features are over-used in the Ruby community, and result in relatively hard-to-read tests.
This is the first of several PRs which will in-line many of the declarations previously made using these idioms.

Refactor aliases_spec.rb to more closely adhere to the Let's Not school of RSpec

---

spec/factory_bot/attribute_spec.rb

Refactor attribute_spec.rb to conform with Let's Not style

---

spec/factory_bot_spec.rb

Refactor factory_bot_spec.rb to conform to Let's Not style

---

spec/factory_bot/null_factory_spec.rb

Refactor null_factory_spec.rb to conform to Let's Not style

---

spec/factory_bot/null_object_spec.rb

Refactor null_object_spec.rb to conform to Let's Not style

---

spec/factory_bot/declaration_list_spec.rb

Refactor declaration_list_spec.rb to conform to Let's Not style

---

spec/factory_bot/disallows_duplicates_registry_spec.rb

Refactor disallows_duplicates_registry_spec.rb to conform to Let's Not style

---

lib/factory_bot/definition.rb
spec/factory_bot/definition_proxy_spec.rb

Refactor definition_proxy_spec.rb to conform to Let's Not style

---

spec/factory_bot/sequence_spec.rb

Refactor sequence_spec.rb to conform to Let's Not style

---

spec/factory_bot/attribute_list_spec.rb

Refactor attribute_list_spec.rb to conform to Let's Not style

---

spec/factory_bot/definition_spec.rb

Refactor definition_spec.rb to conform to Let's Not style

---

GETTING_STARTED.md

Updates documentation to reflect suggestions of RuboCop's class factory naming
https://github.com/rubocop-hq/rubocop-rspec/pull/839

added quotes around factory classes

---

lib/factory_bot.rb

With ruby 2.7 we start seeing the following warnings when running tests
```
/factory_bot/lib/factory_bot.rb:74: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/factory_bot/lib/factory_bot/linter.rb:3: warning: The called method `initialize' is defined here
```
I'm proposing the following changes so that the message is supressed.

fixes deprecation warning on linter.rb

---

spec/factory_bot/factory_spec.rb

Refactor factory_spec.rb to conform to Let's Not style

---

factory_bot.gemspec

For a nice “Changelog” link in the https://rubygems.org/gems/factory_bot sidebar.

Add changelog to gemspec

---

GETTING_STARTED.md

`User` was quoted in the example that presumably shows how to refer to a class directly, which makes the subsequent usage example:
> you can also pass a symbol or string,
confusing.

Change string to User class reference in Getting Started doc

---

lib/factory_bot.rb
lib/factory_bot/definition_hierarchy.rb
lib/factory_bot/internal.rb
lib/factory_bot/syntax/default.rb
spec/factory_bot/internal_spec.rb

This commit deprecates several undocumented top-level FactoryBot
methods:
* callbacks
* configuration
* constructor
* initialize_with
* register_sequence
* resent_configuration
* skip_create
* to_create
factory_bot users are not meant to access these methods directly.
Instead they are available for internal use through the new Internal
module introduced in #1262.
---
While addressing the new deprecation warnings, I tried to make the
delegation a bit more consistent, always delegating to
`FactoryBot::Internal`.
This involved requiring "factory_bot/internal" sooner. To avoid having
to fight with the order of requires and potential circular dependencies,
I moved the default strategy and callback registration out of constants
(this is how they used to be before #1297), so it doesn't matter if …

Deprecate remaining undocumented internal methods

---

GETTING_STARTED.md

I have always found the GETTING_STARTED guide to be a bit overwhelming.
I have troubling finding the information I want, even after having used
factory\_bot for years.
This commit adds a whole bunch of section headings,
then adds a Table of Contents
(autogenerated by https://ecotrust-canada.github.io/markdown-toc/)
to make it easier to navigate this document.
This commit also makes a few small improvements to the content I noticed
while reading through the document.

Add ToC to GETTING_STARTED

---

GETTING_STARTED.md

Add closing bracket after link to 'Dependent Attributes' section, in the 'With other attributes' section.

Add missing closing bracket in GETTING_STARTED.md

---

GETTING_STARTED.md

JRuby section in GETTING_STARTED.md file is very old. So, this PR removes the section.
Resole #1395

[Fix #1395] Remove JRuby things

---

lib/factory_bot.rb
lib/factory_bot/callback.rb
lib/factory_bot/definition.rb
lib/factory_bot/internal.rb
lib/factory_bot/reload.rb
spec/factory_bot/callback_spec.rb

Before this commit, factory_bot registered default callbacks in a global
registry, and offered a `register_callback` method for registering any
custom callbacks (which would be fired within custom strategies).
The idea here seems to have been that we could check against this global
registry and then raise an error when referring to a callback that was
not registered.
However, nobody ever saw this error because we have always had the line:
`FactoryBot::Internal.register_callback(name)`, which registers
callbacks on the fly whenever they are referred to. (I noticed this when
a [change to default callbacks] accidentally duplicated `after_create`
instead of including `before_create`, and we didn't get any tests
failures.)
We have two options here:
1. Preserve the existing behavior by deleting …

Remove code for registering callbacks

---

lib/factory_bot/decorator.rb

This code was added as a workaround to fix namespace issues in one of
the acceptance specs when running with Ruby 1.9.2. [1]
Since then Ruby's constant resolver has been updated and this
non-standard behaviour of `Decorator` is not documented or tested by the
FactoryBot test suite.
So this workaround is no longer needed and the code can be removed.
Removing it improves the test coverage of the project;
Before:
1140 / 1143 LOC (99.74%)
After:
1139 / 1141 LOC (99.82%)
Reference:
[1] https://github.com/thoughtbot/factory_bot/commit/775dc8bd88ae1ea5d746939db5ec7df3c6c276e0

decorator.rb: Remove redundant const_missing class method.

---

lib/factory_bot/null_object.rb

Since `NullObject` inherits from `BasicObject` rather than `Object` it does not need to implement `respond_to?` or `respond_to_missing?` in the way that Rubocop suggests (which assumes that `Object` is the base class).
Rather than writing unused code just to make Rubocop happy, we can tell Rubocop to ignore the `Style/MissingRespondToMissing` cop and delete the useless code.
This improves the test coverage for the project:
Before:
`1140 / 1143 LOC (99.74%)`
After:
`1139 / 1141 LOC (99.82%)`

Remove unused null object code

---

GETTING_STARTED.md

This commit adds top-level documentation for the enum traits feature
adding in #1380

Add documentation for enum traits

---

lib/factory_bot/definition.rb

Fixes #1411
Before this commit, anybody with Active Record enum attributes using
factory_bot 6.0 would have seen an increase in memory every time they
used any trait.
This behavior can be seen with the following benchmark:
```rb
require "bundler/inline"
gemfile(true) do
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gem "factory_bot", "~> 6.0.1"
gem "activerecord"
gem "sqlite3"
end
require "active_record"
require "factory_bot"
require "logger"
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Schema.define do
create_table :posts, force: true do |t|
t.integer :status
end
end
class Post < ActiveRecord::Base
enum status: ("a".."z").to_a
end …
```

Ensure enum traits only get expanded once

---

lib/factory_bot/declaration/association.rb

This commit separates the factory name from the overrides on initialize,
then uses attr_readers throughout instead of manipulating instance
variables.
This is a bit cleaner, and will make it easier to reused the
factory_name and overrides in a future code change.

Use attr_readers in association declaration

---

lib/factory_bot/declaration/association.rb
spec/acceptance/associations_spec.rb

Closes #1391
Along the same lines as #1286, this commit raises a more helpful error
if somebody passes an implicit declaration as an association argument.
Before this commit, an association with an implicit trait passed as an
override attribute:
```rb
person factory: :user, invalid_attribute: implicit_trait
```
Would raise an error `KeyError: Trait not registered: "implicit_trait"`.
This is potentially confusing, since the author probably didn't intend
to define an implicit trait.
After this commit, this will raise a more helpful error:
```
ArgumentError: Association 'person' received an invalid attribute override.
Did you mean? 'invalid_attribute}: :implicit_trait}'
```

Raise more helpful error for invalid attribute

---

lib/factory_bot/decorator.rb
lib/factory_bot/decorator/invocation_tracker.rb
lib/factory_bot/evaluator.rb
spec/acceptance/initialize_with_spec.rb

Ruby 2.7 deprecated passing kwargs when the method expects a hash or passing a hash when the method expects kwargs. In factory_bot, this creates the warning:
```
/Users/hparker/code/factory_bot/lib/factory_bot/decorator/new_constructor.rb:9: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/hparker/code/factory_bot/spec/acceptance/initialize_with_spec.rb:220: warning: The called method `initialize' is defined here
```
We can fix this warning by updating the syntax. We need to include `**kwargs` in the `method_missing` calls when we are on ruby 2.7 or later.
In decorator.rb, adding `**kwargs` alone doesn't work since adding `**kwargs` can change what arguments remain in the `args`.
In this case we have to class eval the method …

Fix ruby 2.7 kwargs warning

---

lib/factory_bot/evaluator.rb
spec/acceptance/associations_spec.rb

closes #1309
closes #1063
It has come up several times over the years that folks want direct
access to the evaluator instance, in most cases to build up more complex
networks of associations. Some folks are already doing this with the
private `@instance` instance variable.
Given that this is such a minimal change, and it makes the library more
flexible for these more complex use cases, this commit adds an
`attr_reader` for the evaluator instance. Now folks can reference it
without reaching into the private api.
Documentation to follow as part of
https://github.com/thoughtbot/factory_bot/issues/1268

Make the evaluator instance public

---

GETTING_STARTED.md
spec/acceptance/associations_spec.rb

This commit makes `Evaluator#association` and `Evaluator#instance`
officially part of the public API of factory\_bot. Folks were already
using these methods, and all of the examples here were inspired by
examples in the various issues mentioned below.
This commit also adds and updates some tests to match the examples in
the documentation, to ensure that these examples will continue to work
as expected.
Closes #1268 by adding documentation for both `Evaluator#association`
and `Evaluator#instance`. The documentation on interconnected
associations is also relevant to #1063, #1255, and #1309.
Closes #1304 by providing multiple alternative approaches to creating
collection associations, and adding a note about reloading the record in
the callback example. This had also come up back in #549. …

Improve documentation for collection associations

---

spec/factory_bot/registry_spec.rb

This essentially reverts commit 3a4d6f48. We removed that test because
we couldn't get it passing on Ruby 2.3 and 2.4, but we have since
removed support for those versions of Ruby.

Add back did_you_mean spec

---

.travis.yml

Ruby 3 is not compatible with Rails 5.0. Rails 5.0 locked to
sqlite3 "~> 1.3.6", but only sqlite3 "<= 1.4.2" is compatible with Ruby
3. [Older versions of sqlite3 referenced `rb_check_safe_obj`][sqlite3],
which raised a warning in Ruby 2.7 and will fail in Ruby 3.0.
Since this combination of tests will always fail, this commit updates
Travis to stop running it.
[sqlite3]: https://github.com/sparklemotion/sqlite3-ruby/pull/277

Avoid running Ruby 3 against Rails 5.0

---

lib/factory_bot/decorator/invocation_tracker.rb
spec/acceptance/initialize_with_spec.rb

Closes #1423
5c071d42 fixed most kwarg deprecation warnings coming from within
factory_bot, but using the Ruby 3-style argument forwarding does not
handle every case.
To handle the case of `initialize_with` being used with a method that
takes a final hash argument, this commit adds an additional branch to
this code to use `ruby2_keywords` for Ruby >= 2.7 and < 3.0. On 3.0 we
use the 3.0-style forwarding.
I added a tests that was outputting a deprecation warning on Ruby 2.7
before this change, but that no longer outputs the warning after this
change.
Yes, this is a bit of a mess, but I don't see a better way. I got
inspiration here from this [fantastic blog post on argument delegating
with Ruby 2.7 and 3][delegating].
[delegating]: …

Address Ruby 2.7 kwargs edge case

---

lib/factory_bot/attribute/dynamic.rb
lib/factory_bot/callback.rb

Ruby has [changed the arity of Symbol#to_proc from -1 to -2][ruby]. This commit
updates some arity checks we have in factory_bot to handle that case.
This should get the Ruby HEAD + Rails 6 tests passing on CI (the Ruby
head with other versions of Rails is still failing for various reasons).
[ruby]: https://github.com/ruby/ruby/commit/5b29ea0845c14092abd866ce0183c52635bade4c

Update arity checks for Symbol#to_proc change

---

GETTING_STARTED.md

I found it confusing that there were line comments under the line
they applied to. I moved them to be above the line so that it was
clearer which code they were referring to.
I also adjusted the language a little bit for clarity.
Signed-off-by: Randy Barlow <rbarlow@credible.com>

Clarify some examples in GETTING_STARTED

---

GETTING_STARTED.md

Signed-off-by: Randy Barlow <rbarlow@credible.com>

Fix a typo in GETTING_STARTED.md

---

GETTING_STARTED.md

This swaps the string and constant examples for the `class:` option, treating
the string example as the normal case and the constant example as an
alternate approach with caveats.
I have seen a number of problems with using constants, and
[rubocop-rspec][] even has a custom cop to prevent this.
I could almost remove the constant example, except that a lot of folks
are still using it and there may be room for confusion if it totally
disappears. Instead, I present it with a note about the potential
performance problem.
[rubocop-rspec]: https://github.com/rubocop-hq/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/factory_bot/factory_class_name.rb
cc @HParker

Prefer string argument to class option [ci skip]

---

NEWS.md

See https://github.com/thoughtbot/factory_bot/issues/1462#issuecomment-768674537 and https://github.com/thoughtbot/factory_bot/issues/1409

Document removal of "abstract factories" in 6.0.0

---

README.md

Why:
----
The badge link is pointing to a non existent location. And the query for the workflows lists all builds and not only the main branch one.
This PR:
----
Updates the badge and workflow link according to [this guide](https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge)

Fix ci badge and workflows query link

---

lib/factory_bot/decorator/invocation_tracker.rb
lib/factory_bot/evaluator.rb

* (*args, **kwargs) delegation is incorrect in 2.7, only ruby2_keywords works on 2.7.
* See https://eregon.me/blog/2021/02/13/correct-delegation-in-ruby-2-27-3.html or https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
I noticed this while investigating https://github.com/oracle/truffleruby/issues/2258.

Fix delegation

---

.github/workflows/build.yml

This commit stops running tests against ruby-head. We mostly don't look
at these test results, and until there's some support for [allowed
failures][] I'd rather skip them so we can get a green build.
This commit also removes the failing jruby + Rails main combination,
although it leaves the CRuby + Rails main tests in place since they are
passing. Rails main is pretty stable, and folks are running it in
production, so I'd like to keep test coverage there if possible.
[allowed failures]: https://github.com/actions/toolkit/issues/399

Remove tests that are allowed to fail

---

.github/workflows/build.yml

Why:
----
The trigger for the build job is either a `push` or a `pull_request`. When a pull request is opened against master two CI run start, since
both triggers are valid.
This Commit:
----
- Skip the build job if the event is a pull request made from the same repository. Since a CI build job hast started already because a push trigger was detected.

Skip double CI build on main branch pull requests

---

lib/factory_bot/attribute_assigner.rb
spec/acceptance/add_attribute_spec.rb

This is a fix to make it possible to define an attribute named `new` (which is a bad name for an attribute by the way =)).
```
FactoryBot.define do
factory :post do
add_attribute(:title) { "Title" }
add_attribute(:sequence) { "Sequence" }
add_attribute(:new) { true }
end
end
FactoryBot.attributes_for(:post)
FactoryBot.build(:post)
```

Fix default value for attribute named `new`

---

GETTING_STARTED.md

Follow-up to https://github.com/thoughtbot/factory_bot/pull/1446
looks like `name` should be used here (in line with this and other examples), not `author_last_name`, this is how it was suggested in [this PR review comment](https://github.com/thoughtbot/factory_bot/pull/1446#discussion_r516157987) but got mixed up in the end somehow

fix attribute name mismatch in the associations example

---

Gemfile.lock
gemfiles/5.0.gemfile.lock
gemfiles/5.1.gemfile.lock
gemfiles/5.2.gemfile.lock
gemfiles/6.0.gemfile.lock
gemfiles/6.1.gemfile.lock
gemfiles/main.gemfile.lock

Why:
----
Dependabot issued a warning about a development dependency security update for the [rexml] gem used by rubocop.
[rexml]: https://github.com/advisories/GHSA-8cr8-4vfw-mr7h
This Commit:
----
- Ran `bundle update rexml` on the root path to update `rexml` from 3.2.4 => 3.2.5
- Updated static Gemfiles to reflect the same version

Update rexml following dependabot alert

---

lib/factory_bot/aliases.rb

FactoryBot relies on ruby >= 2.5, so we can use Regexp#match? that does not allocate MatchData
Allocations measured with heap-profiler gem in an internal test suite with 7497 examples and 149470 calls to aliases_for:
allocated memory by file
-----------------------------------
59.79 MB  factory_bot-6.1.0/lib/factory_bot/aliases.rb
38.27 MB  factory_bot-6.1.0/lib/factory_bot/aliases.rb
allocated objects by file
-----------------------------------
896880  factory_bot-6.1.0/lib/factory_bot/aliases.rb
597940  factory_bot-6.1.0/lib/factory_bot/aliases.rb
The remaining allocations are mainly caused by https://github.com/thoughtbot/factory_bot/blob/9e58a34e1e584dfd41b7327969b06c7a7c9b7559/lib/factory_bot/aliases.rb#L14
In the test suite I used, I noticed that `attribute` values are repeated …

Use match? in FactoryBot#aliases_for to save allocations

---

GETTING_STARTED.md

Fixes #1444 and #1479
Add a short note in GETTING_STARTED.md about the need to save the record
after it has been modified

Update GETTING_STARTED: include note about saving in `create_list`

---

spec/acceptance/associations_spec.rb
spec/factory_bot/attribute/association_spec.rb
spec/factory_bot/attribute/dynamic_spec.rb
spec/factory_bot/declaration/implicit_spec.rb
spec/factory_bot/definition_proxy_spec.rb

Hello! Thank you for this awesome project!
This PR has fixed some typo.
- "delcaration" -> "declaration"
- "Ususually" -> "Usually"
- "assocition" -> "association"
- "vaue" -> "value"

Fix some typo

---

.github/workflows/build.yml

The latest TruffleRuby release (22.2.0) is compatible with CRuby 3.0 so now they will be check on CI against the same Rails versions.
TruffleRuby CI builds fail on Rails 5.0, 5.1 and 5.0 because of missing `rb_check_safe_obj` function. It was removed in CRuby 3.0 (https://github.com/ruby/ruby/commit/ada2f71c70bb11f1d71485e2090ce36872608217)

Don't run CI builds on TruffleRuby and Rails 5.0, 5.1, and 5.2

---

.github/workflows/build.yml

The version 3.x appears to be due to the following:
- https://github.com/actions/checkout/pull/689
There have been no breaking changes, and we seem to have no problem keeping up with the latest version.

Update actions/checkout version to v3

---

.github/ISSUE_TEMPLATE/bug_report.md
.gitignore
CONTRIBUTING.md
GETTING_STARTED.md
README.md

This renames all references to `master` to `main`. The `master` branch
is no longer up to date, so these links go to outdated docs. There was
one in `.gitignore` that I removed entirely, as it looks like the
`.lock` files in the `gemfiles/` directory are intentionally checked in.

rename references master -> main

---

GETTING_STARTED.md

See https://github.com/thoughtbot/factory_bot/issues/1536

Add 'to_sym' to CustomStrategy in GETTING_STARTED

---

features/support/env.rb
spec/factory_bot/find_definitions_spec.rb
spec/spec_helper.rb

The truffleruby + Rails 7.0 build was failing because of some kind of simplecov incompatibility. I don't think we need to run simplecov on the truffleruby and jruby builds (we might not need it on any build—it prints some output but doesn't affect the build status at all—but I figured I'd leave it alone for now in case somebody is looking at it).
I needed to add a fileutils require to one test that was presumably getting implicitly required before via simplecov.

Don't run simplecov on alternate Ruby

---

cucumber.yml

Otherwise we see this every time we run cucumber:
```
┌──────────────────────────────────────────────────────────────────────────┐
│ Share your Cucumber Report with your team at https://reports.cucumber.io │
│                                                                          │
│ Command line option:    --publish                                        │
│ Environment variable:   CUCUMBER_PUBLISH_ENABLED=true                    │
│ cucumber.yml:           default: --publish                               │
│                                                                          │
│ More information at https://reports.cucumber.io/docs/cucumber-ruby       │
│                                                                          │
│ To disable this message, specify …
```

Disable cucumber publish message

---

lib/factory_bot/definition.rb
lib/factory_bot/registry.rb
spec/acceptance/traits_spec.rb
spec/factory_bot/registry_spec.rb
spec/support/matchers/raise_did_you_mean_error.rb

did_you_mean tests started failing on Ruby 3.2 because of https://bugs.ruby-lang.org/issues/18564.
This gets did_you_mean working again for Ruby 3.2 by adding the original KeyError's key and receiver over to the custom KeyError. That way the did_you_mean can get added to the custom KeyError via the new detailed_message.
Once this is merged we can add Ruby 3.2 to the test matrix

Pass key and receiver to custom key errors

---

GETTING_STARTED.md
README.md

Thank you for your years of service, `GETTING_STARTED.md`. You're in a better place now.

Link to the book

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
GETTING_STARTED.md
NAME.md
NEWS.md
README.md
RELEASING.md

Since [the deprecation of `GETTING_STARTED.md`](https://github.com/thoughtbot/factory_bot/pull/1574), I've gotten better at noticing when people online link to it on the old `master` branch. That version does not have the deprecation notice linking to the new docs, nor does it have any changes made in the past couple years.
This PR targets the `master` branch and adds a warning to the top of each Markdown file with a link to it on the `main` branch. It doesn't directly link to the news docs, which is deliberate so that we don't potentially have to update the `master` branch again in the future (if we move the docs again, for example).
If this PR is merged, I plan to make a similar change in [factory_bot_rails](https://github.com/thoughtbot/factory_bot_rails).

Warn about viewing docs on old `master` branch

---

NEWS.md

In a sufficiently large codebase, the automatic definition of traits for Active Record enum  (#1380) may result in more combinations being checked by `FactoryBot.lint`. This breaking change may not be obvious because the first impression of the error messages may be "these factories were passing before the upgrade but now failing ?", while the truth is that they don't exist before the upgrade. It took me a while to realize this so I hope adding this note could help people be aware of this situation when upgrading.

Document 6.0.0 may break `FactoryBot.lint`

---

NEWS.md
docs/src/ref/build-strategies.md
lib/factory_bot/strategy/stub.rb

I was surprised to find that #destroyed? returns nil
instead of false when I build_stubbed.  I don't see
a reason for it in the commit history nor in Rails,
so I thought it was fair game for this PR.

fix(Stub): align #destroyed with #new_record/#persisted

---

GETTING_STARTED.md
docs/src/activesupport-instrumentation/summary.md
lib/factory_bot/definition.rb
spec/acceptance/activesupport_instrumentation_spec.rb

Related to [comment on thoughtbot/factory_bot#1586][]
---
Publish Active Support Notifications under the
`factory_bot.compile_factory` key.
They payload for that event is a `Hash` with keys:
* `name:` - the name of the Factory
* `class:` - the Ruby class the Factory constructs instances of
* `attributes:` - a `FactoryBot::AttributesList` instance for the available attributes
* `traits:` - an Array of `FactoryBot::Trait` instances for the available traits
[comment on thoughtbot/factory_bot#1586]: https://github.com/thoughtbot/factory_bot/pull/1586#issuecomment-1674003814

Publish `factory_bot.compile_factory` notification

---

factory_bot.gemspec

[Ruby gems](https://rubygems.org/gems/factory_bot) doesn't show the link to the changelog.
I thought this was especially important since the filename is unconventional, it would speed up the workflow of this gem's users.

Chore - Add link to the changelog 

---

GETTING_STARTED.md
docs/src/associations/association-overrides.md
docs/src/sequences/inline-sequences.md
docs/src/using-factories/attribute-overrides.md
docs/src/using-factories/build-strategies.md
spec/acceptance/attributes_for_destructuring.rb
spec/acceptance/attributes_for_spec.rb

Ruby 2.7 introduced [numbered block parameters][], and 3.0 introduced [Hash literal value omission][], so document how they integrate with Factory Bot.
[numbered block parameters]: https://ruby-doc.org/core-2.7.1/Proc.html#class-Proc-label-Numbered+parameters
[Hash literal value omission]: https://docs.ruby-lang.org/en/3.1/syntax/literals_rdoc.html#label-Hash+Literals

Document integration with 2.7 and 3.0 syntactic sugars

---

lib/factory_bot/strategy/stub.rb
spec/acceptance/stub_spec.rb

This is based on #1514 and fixes #1498.
The only things i did, compared to #1514, are the following:
- rebased on main
- added one more guard clause, to ensure that the worst-case result if the relevant rails API is ever removed is the same lack of UUID support that we have currently
The relevant rails API hasn't changed since PR #1514 was created 2 years ago. It would be nice to finally get support for UUIDs. 😊

Support uuids in build_stubbed

---

spec/acceptance/defining_methods_inside_a_factory_spec.rb
spec/acceptance/modify_factories_spec.rb
spec/factory_bot/definition_proxy_spec.rb
spec/support/matchers/raise_did_you_mean_error.rb

RSpec's `expect` has two forms:
- scalar: `expect(result).to be_truthy`
- block: `expect { thunk }.not_to raise_error(RuntimeError)`
So what happens when you mix them?
```ruby
thunk = -> { 1 / 0 }
expect(thunk).not_to raise_error(RuntimeError)
```
If you do that, RSpec complains:
> The implicit block expectation syntax is deprecated, you should pass a
> block rather than an argument to `expect` to use the provided block
> expectation matcher or the matcher must implement
> `supports_value_expectations?`
The easy solution is to pass the Proc as a block, using `&`:
```
thunk = -> { 1 / 0 }
expect(&thunk).not_to raise_error(RuntimeError)
```

Pass block to `expect` as needed

---

lib/factory_bot/definition.rb
lib/factory_bot/trait.rb
spec/acceptance/activesupport_instrumentation_spec.rb

#1587 published `factory_bot.compile_factory notification`.
That maked to be able tracking the attributes and traits, e.g. https://github.com/thoughtbot/factory_bot_rails/pull/419 .
But when using trait the payload has no class, so assign definition's class to defined_traits.
Fix https://github.com/thoughtbot/factory_bot_rails/issues/431

Assign klass to defined_traits to pass it's class to ActiveSuport::Notifications

---

lib/factory_bot/definition.rb
lib/factory_bot/internal.rb
spec/acceptance/activesupport_instrumentation_spec.rb
spec/factory_bot/internal_spec.rb

We fixed the error that `defined_traits` had no class in #1600 .
But we can declare traits also in top level and mixin them as `base_traits` and `additional_traits`, like:
```ruby
FactoryBot.define do
trait :email do
email { "#{name}@example.com" }
end
factory :school, traits: [:email] do
name { "Charlie" }
end
factory :company do
name { "Charlie" }
end
end
FactoryBot.build(:school)
FactoryBot.build(:company, :email)
```
The traits declared at the top level have their class determined when they are used, so assign the definition klass when the traits are used to pass their class to ActiveSuport::Notifications.
Re Fix https://github.com/thoughtbot/factory_bot_rails/issues/431

Assign klass to global traits when find by name

---

lib/factory_bot/strategy/stub.rb
spec/acceptance/stub_spec.rb

Some "models" may not have an ID setter at all. This PR ensures that `build_stubbed` only tries to set the ID if the model does have an ID setter (i.e. does have an `#id=` method).

Support models without ID setters in build_stubbed

---

.github/workflows/build.yml
.github/workflows/docs.yml

This Pull Request has been created because [actions/checkout](https://github.com/actions/checkout) has been bumped to [version 4](https://github.com/actions/checkout/releases/tag/v4.0.0) on the 04/09/2023
This Pull Request changes all the CI that use `actions/checkout@v3` and `actions/checkout@v2` in favour of `actions/checkout@v4`

Bump github actions/checkout to v4

---

.github/workflows/build.yml

The `error_highlight` gem was added in Ruby 3.1, which means we cannot disable it on Ruby 3.0 or earlier.
So long as we support those versions, let's stop disabling it. This is the fastest way to get CI passing again.

Stop passing disable-error_highlight

---

spec/factory_bot/definition_proxy_spec.rb

We don't actually care about the specific letters used in Ruby's `NoMethodError` exception message. We do care about the important parts, though: the method name, the object, and that "Did you mean" worked.

Relax the exception message check

---

docs/src/ref/modify.md

The [FactoryBot.modify](https://thoughtbot.github.io/factory_bot/ref/modify.html) reference page on the documentation site has a broken link for "the guide".
This commit fixes the link.

Fix broken link on ref/modify.html page in docs

---

factory_bot.gemspec

See #1612
Closes #1614
I would suggest against yanking the affected version. Doing so will result in installs for those that already upgraded not working anymore so you get another disruption for free. It's been a month since that release and it would have been better to do this as early as possible instead.

Bump minimum required ruby version to 3.0

---

docs/src/ref/factory.md

Fixes #1621 
Links within the docs for the [factory reference](https://github.com/thoughtbot/factory_bot/blob/377d699b3753113cc9eb4ebc5fb3cc54d4397cea/docs/src/ref/factory.md) are broken.
This changes the markdown to make the links work. Links also send to correct heading on page where applicable.

fix: issue 1621 broken links in ref/factory.md

---

.github/workflows/dynamic-readme.yml
README.md

In the templates repo, the update-templates workflow has been updated to accommodate repositories that have main branch rules (like factory_bot). To generate the README dynamically, you’ll need to merge a PR with the README changes. That will trigger the GitHub workflow
The PR won’t be generated if the footer content does not have any differences from the template. The PR will only be opened if there’s an update to the footer snippet.
In this PR, we are limiting this workflow to be triggered only when README changes have been merged to main (where the snippet lives).

Only run this workflow if the README has been updated

---

docs/src/traits/using.md

The https://thoughtbot.github.io/factory_bot/traits/using.html page has a small typo.
The second code block uses the `active` trait, but it's not defined in the Factory.
This MR adds the missing trait.

Fix the factory definition in traits documentation

---

factory_bot.gemspec

They were dropped from CI in #1612. Also see #1614 and #1622.
Noticed while adding 7.2 to CI.

Bump the minimum required activesupport version to 6.1

---

NEWS.md
lib/factory_bot/linter.rb
spec/acceptance/lint_spec.rb

Prior to this change `FactoryBot.lint!` execution can trigger sequential `FactoryBot.create` calls made within the same test (either Minitest `test` or RSpec `it` blocks).
This can result in linting violations for records that have database-level uniqueness constraints.
This commit introduces the private `Linter#in_transaction` method to wrap the executing block within an [ActiveRecord::Base.transaction][] block that concludes with raising an [ActiveRecord::Rollback][] error.
After this change, executions no longer contest with database-level uniqueness constraints.
[ActiveRecord::Base.transaction]: https://edgeapi.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html#method-i-transaction
[ActiveRecord::Rollback]: https://edgeapi.rubyonrails.org/classes/ActiveRecord/Rollback. …

Execute `FactoryBot.lint!` in database transactions

---

.github/workflows/build.yml

GitHub Actions has been running the lint twice in Pull Requests: once following the `on push` trigger, once following `on pull_request`. This duplication is currently avoided when running tests by an `if` rule, which skips if the event isn't a push or the Pull Request doesn't come from a fork.
This commit removes the `if` rule, and limits the `push` builds to the `main` branch. That will ensure that merged Pull Requests will trigger a build, and that any Pull Request activity will also trigger a build. Being a global rule for the whole build, `standard` will not run twice anymore.

Limit `push` builds to the `main` branch

---

spec/acceptance/lint_spec.rb

Update for testing in Ruby 3.4
- file:   spec/acceptance/lint_spec.rb:188
THE PROBLEM THIS FIXES
Ruby 3.4 backtrace locations now include both the object and method names in the format:
"<object_name>#<method_name>.
So a backtrace location with "...`save!`" in ruby 3.3, now becomes "... 'InvalidThing#save!'" in Ruby 3.4.
THE SOLUTION
The solution was to update the test regex to allow for either option:
%r{#{__FILE__}:\d*:in ('InvalidThing#save!'|`save!')}

Small update to "verbose linting" spec to allow for Ruby 3.4 backtrace changes

---

lib/factory_bot/strategy/stub.rb
spec/acceptance/stub_spec.rb

Ensures build_stubbed generates a record with equal created_at and updated_at.
Calling `.build_stubbed` on factories with entities that have created_at and updated_at assigns a slightly different time for each one of then because the code calls `Time.current` twice.
I think the expected behavior should be for them to be exact the same.
There are two concerns with the current solution:
1. We would be calling `Time.current` even if created_at and updated_at don't exist on the entity;
2. ~~It might be a problem that we're assigning the same object to both timestamps, should we `dup` updated_at?~~ (edit: dates are immutable, never mind :grimacing: :face_with_peeking_eye:).
I preferred to ask if these are valid concerns before investigating how to solve them.

Fix build_stubbed timestamps being different

---

lib/factory_bot/find_definitions.rb

The comment for `definition_file_paths` is incorrect; all matching factory paths will be loaded. This is also documented correctly at https://thoughtbot.github.io/factory_bot/ref/find_definitions.html

Fix definition_file_paths comment

---

README.md

Full disclosure: one of these is my own gem :) but the other, I have no connexion with!
https://github.com/donny741/ruby-lsp-factory_bot
https://github.com/johansenja/ruby-lsp-rails-factory-bot

Add ruby-lsp extensions to `Useful Tools` in README.md

---

README.md

The "Transitioning from factory\_girl" guide points to a tag that was renamed at some point, and thus is broken.
This commit points the URL to the correct tag name.
Closes #1744

Fix "Transitioning from Factory Girl" guide link

---

lib/factory_bot/definition_proxy.rb
spec/acceptance/defining_methods_inside_a_factory_spec.rb

Fixes: #1751 
A new `attr_reader :definition` was added to FactoryBot::DefinitionProxy.
When trying to set an instance attribute named `:definition` using `:method_missing`, it's targeting the proxy `:definition` rather than creating an attribute, leading to an exception
I've removed the `:instance` method and changed all  references to  `@instance` 
🤔

FactoryBot::DefinitionProxy: remove `definition` `attr_reader`

---

.irbrc
bin/console
bin/setup

Developer helper to quickly open an IRB console with the gem code already loaded: `bin/console`
It also has a built-in `reload!` method that will reload  a fresh copy of the files.
There is no change to any gem code.
- the `reload!` method is define in `.irb`
- the console is configured and launched from `bin/console`
- `.setup` ensures the shell environment:
-  fails early
- only uses "\n\t" as line breaks
- prints the result of each command to the console, for easier debugging.
---
It's easier to debug using an IDE with an integrated debugger, but sometimes you just want to play with the code 🚀

Developer Console Feature

---

lib/factory_bot/evaluator.rb
lib/factory_bot/syntax/methods.rb
spec/acceptance/sequence_context_spec.rb

Fixes: #1754
The issue was `.increment_sequence` within `FactoryBot::Evaluator` was un-defining, then replacing,  the `.increment_sequence` method included from `FactoryBot::Syntax::Methods`, but there was a parity miss-match.
- Refactored :increment_sequence in both modules to remove the URI requirement.
- Updated sequence specs for both direct and implicit strategy use.
- FactoryBot.build(:user)
- build(:user)
No change to the user API.

BugFix: standardise parity on :increment_sequence

---

lib/factory_bot/evaluator.rb
lib/factory_bot/registry.rb

Reviewing the Active Support usage, I noticed two `require` calls that are unnecessary:
We don't use the `Hash#except!` method defined on `active_support/core_ext/hash/except.rb`, nor the `Hash#with_indifferent_access` defined on `active_support/hash_with_indifferent_access.rb`.
We _do_ use the `HashWithIndifferentAccess` class directly, so we're now requiring `"active_support/hash_with_indifferent_access"` instead.

Cleanup Active Support core extensions

---

docs/src/SUMMARY.md
docs/src/callbacks/callback_order.md
docs/src/callbacks/summary.md
docs/src/ref/hooks.md
lib/factory_bot/factory.rb
spec/acceptance/callbacks_spec.rb
spec/factory_bot/definition_proxy_spec.rb
spec/support/containers/test_log.rb

Fixes: #1694 
Continues: #1695 
Continuing on from #1695 it was decided that `before(:all)` and `after(:all)` callbacks would provide a solution, without exposing context internals.
Both callbacks are defined in the usual way, and operate through the normal callback process.
`before(:all)` callbacks are triggered before the factory is run. Calling it with `before(:all){ |instance, context| ... }` will provide the factory context, but both the `instance` and `context.object` will be nil.
`after(:all)` callbacks are triggered once the factory has completed it's strategy. In this case, the `instance` and `context.object` are populated as normal.
The only code changes are two new lines to trigger the :before and :after callbacks in the `Factory#run` method, and a little restructuring to …

FEATURE: Before(:all) and after(:all) callbacks added

---

docs/src/sequences/initial-value.md
lib/factory_bot/sequence.rb
spec/acceptance/sequence_setting_spec.rb
spec/acceptance/sequence_spec.rb
spec/factory_bot/sequence_spec.rb

Note: This is a re-implementation of the changes in https://github.com/thoughtbot/factory_bot/pull/1674 to remove the need to use a `lazy` kwarg.
In order to be able to use factory_bot to generate seeds for a database where the database might not have the schema set up yet or might have data already populated, it is useful to be able to defer assigning the initial value to a sequence until it is needed. 
Currently, factory_bot needs the initial value of the sequence to be defined when the factory file is loaded.
This lazy loading behaviour has been very handy for use when we need to create objects that have unique sequential id in formats specific to third party systems. We can use these factories in our development and CI environments without having to think about which values have …

Allow the initial value of a sequence to be lazy loaded

---

Gemfile.lock
NEWS.md
RELEASING.md
lib/factory_bot/version.rb

- updates the `RELEASING.md` instructions
- updates `NEWS.md` with line breaks to improve markdownlint linting issues
- updates `NEWS.md` with the release notes for v6.5.5

Build: release v6.5.5
