thoughtbot/factory_bot

- README.md
Since the batch was not able to display, it was changed to a new link.
> Fix code climate badge

- lib/factory_girl/syntax/methods.rb
- spec/acceptance/sequence_spec.rb
I use FactoryGirl in my work project and at one day I needed a list of phone numbers from sequence and I wrote `generate_list(:phone_numbers, 10)` but FactoryGirl has not this method. I decided that method might be useful for me and somebody else.
Thank you for your time to review my PR.
> method for generating list of values in sequence

- lib/factory_girl/strategy/stub.rb
- spec/acceptance/build_stubbed_spec.rb
> Add default updated_at column

- lib/factory_girl/syntax/methods.rb
Super small update to the comments. It just happened to trip me up for a split second, so I thought I'd offer a quick change. Plus it makes it consistent with the other @param descriptions.   :)
> Small clarifying updates to comments

- lib/factory_girl/evaluation.rb
- lib/factory_girl/factory.rb
- spec/acceptance/create_spec.rb
Feature request from https://github.com/thoughtbot/factory_girl/issues/1010. I'm happy to rework this if we want to take a different approach.
> Pass evaluator to to_create

- NAME.md
- README.md
Resolves https://github.com/thoughtbot/factory_bot/issues/1060
> Update naming history

- .travis.yml
- Appraisals
- gemfiles/3.2.gemfile
- gemfiles/3.2.gemfile.lock
- gemfiles/4.0.gemfile
- gemfiles/4.0.gemfile.lock
- gemfiles/4.2.gemfile
- gemfiles/4.2.gemfile.lock
- gemfiles/5.0.gemfile
- gemfiles/5.0.gemfile.lock
- gemfiles/5.1.gemfile
- gemfiles/5.1.gemfile.lock
Add Ruby 2.4.2 and Rails 5.1, and update Ruby 2.2 and 2.3 patches.
> Update Ruby and Rails versions tested

- UPGRADE_FROM_FACTORY_GIRL.md
Now the script will work for lines containing multiple `FactoryGirl`.
> Add global flag to sed command for migration

- README.md
> Update readme, hire us link

- .travis.yml
Co-authored-by: Tsukuru Tanimichi <info+github@ttanimichi.com>
Co-authored-by: Daniel Colson <danieljamescolson@gmail.com>
> CI against Ruby 2.5.1

- lib/factory_bot/strategy/stub.rb
- spec/acceptance/build_stubbed_spec.rb
- spec/factory_bot/strategy/stub_spec.rb
Solves https://github.com/thoughtbot/factory_bot/issues/1125
> Do not add missing timestamps when using build stubbed strategy

- .yardopts
- factory_bot.gemspec
This PR fixes issue #1172. Please see issue as the description of this PR.
> Fix missing docs (#1172)

- .travis.yml
These tests have been failing for a while now, and I don't plan on
debugging the failures. If we can get them passing again, I would be
happy to add them back.
> Stop running Travis with Rubinius

- lib/factory_bot/attribute_assigner.rb
i think aligned better easy to read
my english very weak … i`m sorry!
> adjust style

- README.md
This saves the user the need to navigate to another site.
> Use GH to show the GETTING_STARTED

- README.md
Check the discussion: https://github.com/thoughtbot/factory_bot/issues/1296.
> Add useful tools section to README

- GETTING_STARTED.md
This is a very small documentation fix for clarity.
> Mark as code for association strategy

- .github/ISSUE_TEMPLATE.md
- .github/REPRODUCTION_SCRIPT.rb
I often find myself asking for more information about an issue and
especially for ways to reproduce bugs. This template and sample
reproduction script will hopefully help us get more information from the
beginning.
> Add issue template

- spec/support/macros/define_constant.rb
Removed some extra boilerplate RSpec support code.
> Refactor define constant macros

- GETTING_STARTED.md
Fixed Markdown Syntax in GETTING STARTED.md. :)
> Fix Markdown Syntax in GETTING STARTED.md

- UPGRADE_FROM_FACTORY_GIRL.md
Added links to PRs so that they are clickable.
> Make PR links clickable

- GETTING_STARTED.md
> Fix typo in getting started

- GETTING_STARTED.md
This PR provides a very brief introduction to the transient attributes feature. To me (personally) the feature was unclear until I researched it further, so I believe a small introduction would be reasonable to add.
> Introduce transient attributes in the GETTING_STARTED guide.

- GETTING_STARTED.md
Just happened upon this while reading.
> Fix indentation in GETTING_STARTED.md

- .github/workflows/build.yml
> Improve Github Actions labels

- .github/workflows/build.yml
All jobs pass on TruffleRuby: https://github.com/eregon/factory_bot/actions/runs/823666810
> Add TruffleRuby in CI

- GETTING_STARTED.md
Hey, comrades! Many thanks for the great tool!
I've created this PR just to improve the Getting Started guide a little. I found that often the pattern for sequences is to use an array to cycle through its values. So I believe it will save some time for developers if the proper way to use arrays will be mentioned in docs. But I'm not sure if I mentioned the best one 😀
`sequence :priority, %i[low medium high urgent].cycle`
What do you think?
> Update GETTING_STARTED.md with mention Array#cycle

- GETTING_STARTED.md
It's not just factory_bot 5, but 6, and presumably 7, etc until the end of all time and the atomic scaffolding of the universe breaks down.
> [DOC] Clarify association build strategy behavior

- .hound.yml
* Hound is no longer used for linting and now the project uses standard
* Remove unused hound.yml file
> Remove hound.yml file

- Gemfile.lock
- factory_bot.gemspec
- lib/factory_bot/evaluation.rb
- lib/factory_bot/factory.rb
- spec/factory_bot/factory_spec.rb
Alternative to #1610. This dependency really isn't doing much and is trivial to replace.
> Remove dependency on observer

- docs/src/ref/lint.md
Fixes https://github.com/thoughtbot/factory_bot/issues/1595
> Fix linting-factories link in ref/lint.md

- CODEOWNERS
It's been a pleasure working with all of you.
> Drop myself from CODEOWNERS

- .github/workflows/build.yml
👋  Thanks for the review in advance
- This PR Adds Ruby 3.3 to the CI matrix.
> Add Ruby 3.3 to CI

- CODEOWNERS
Add myself, @sarahraqueld, @smaboshe and @minaslater as the new maintainers.
> Add new maintainers to CODEOWNERS

- CODEOWNERS
Supporting projects across organizations is difficult.
> Adds @doodlingdev to codeowners list

- CODEOWNERS
@neilvcarvalho is joining the team as a maintainer, and replacing me. I hope to still contribute occasionally!
> Update CODEOWNERS, introduce @neilvcarvalho

- CODEOWNERS
Remove @smaboshe from factory bot CODEOWNERS
> Update factory bot CODEOWNERS
